<a href="https://colab.research.google.com/github/Ayushisinhaxvii/create-a-graph-using-collab-/blob/main/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
#split it in features and labels
x=iris.data
y=iris.target
iris=datasets.load_iris()
#split it in features and labels
x=iris.data
y=iris.target
print(x,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
iris=datasets.load_iris()
#split it in features and labels
x=iris.data
y=iris.target

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.size)
print(x_test.size)
print(y_train.size)
print(y_test.size)



[[5.7 2.5 5.  2. ]
 [5.1 2.5 3.  1.1]
 [5.8 2.7 4.1 1. ]
 [6.1 3.  4.9 1.8]
 [7.9 3.8 6.4 2. ]
 [6.3 3.4 5.6 2.4]
 [5.  3.4 1.5 0.2]
 [6.3 2.5 5.  1.9]
 [7.3 2.9 6.3 1.8]
 [5.4 3.9 1.3 0.4]
 [6.8 3.  5.5 2.1]
 [6.6 2.9 4.6 1.3]
 [7.6 3.  6.6 2.1]
 [5.8 2.7 5.1 1.9]
 [5.6 2.9 3.6 1.3]
 [7.2 3.  5.8 1.6]
 [4.9 2.5 4.5 1.7]
 [5.4 3.4 1.7 0.2]
 [6.8 3.2 5.9 2.3]
 [6.7 2.5 5.8 1.8]
 [5.5 2.5 4.  1.3]
 [7.7 2.6 6.9 2.3]
 [6.3 2.9 5.6 1.8]
 [5.1 3.8 1.5 0.3]
 [6.4 2.7 5.3 1.9]
 [5.2 3.4 1.4 0.2]
 [5.5 2.6 4.4 1.2]
 [5.  2.3 3.3 1. ]
 [6.3 2.8 5.1 1.5]
 [6.2 3.4 5.4 2.3]
 [5.  3.5 1.6 0.6]
 [5.5 2.4 3.8 1.1]
 [6.6 3.  4.4 1.4]
 [5.  3.4 1.6 0.4]
 [6.5 2.8 4.6 1.5]
 [6.1 2.8 4.  1.3]
 [6.1 2.8 4.7 1.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [6.3 2.5 4.9 1.5]
 [6.2 2.8 4.8 1.8]
 [5.5 2.4 3.7 1. ]
 [6.  2.7 5.1 1.6]
 [5.  3.2 1.2 0.2]
 [5.7 3.  4.2 1.2]
 [6.1 3.  4.6 1.4]
 [5.1 3.5 1.4 0.3]
 [7.7 3.8 6.7 2.2]
 [6.3 3.3 6.  2.5]
 [7.1 3.  5.9 2.1]
 [5.8 2.6 4.  1.2]
 [5.7 2.8 4.5 1.3]
 [4.9 2.4 3.